apiVersion: apps/v1
kind: Deployment
metadata:
  name: facerec
spec:
  selector:
    matchLabels:
      run: facerec
  replicas: 1
  template:
    metadata:
      labels:
        run: facerec
    spec:
      containers:
      - name: facerec-container
        image: docker.pkg.github.com/ankur6ue/facerec/docker.face_det:0.1
      imagePullSecrets:
      - name: github-docker-reg-cred

