apiVersion: apps/v1
kind: Deployment
metadata:
  name: facerec
spec:
  selector:
    matchLabels:
      run: facerec
  replicas: 2
  template:
    metadata:
      labels:
        run: facerec
    spec:
      containers:
      - name: facerec-container
        image: docker.pkg.github.com/ankur6ue/facerec/docker.face_det:0.1
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 800m
        # will always pull latest image
        imagePullPolicy: Always
      imagePullSecrets:
      - name: github-docker-reg-cred

